name: GoogleOfficeLocations
description: An app featuring Google office locations on Map using the Flutter SDK.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.11
  http: ^0.12.0+1
  json_serializable: ^2.0.2
  cupertino_icons: ^0.1.2
  permission_handler: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0
  build_runner: ^1.2.7

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: third_party/Raleway-Regular.ttf
